### PR TITLE
Add Autogenerated API docs

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
Add Yarn and GitHub workflow config for building docs to GitHub Pages. When it's approved I can connect up the GitHub pages part.

### CODE REVIEW

**Comment by ntn-x2** [comment]
This is the output of running `yarn build:docs`:

```
[warning] You are running with an unsupported TypeScript version! If TypeDoc crashes, this is why. TypeDoc supports 4.6, 4.7, 4.8, 4.9, 5.0, 5.1
[warning] DipCommitmentProofRes, defined in ./src/utils.ts, is referenced by utils.generateDipCommitmentProof.generateDipCommitmentProof but not included in the documentation.
[warning] DipDidSignatureRes, defined in ./src/utils.ts, is referenced by utils.generateDipDidSignature.generateDipDidSignature but not included in the documentation.
[warning] DipIdentityProofRes, defined in ./src/utils.ts, is referenced by utils.generateDipIdentityProof.generateDipIdentityProof but not included in the documentation.
[warning] ProviderStateRootProofRes, defined in ./src/utils.ts, is referenced by utils.generateProviderStateRootProof.generateProviderStateRootProof but not included in the documentation.
[warning] DipCommitmentProofOpts, defined in ./src/utils.ts, is referenced by utils.generateDipCommitmentProof.generateDipCommitmentProof.params but not included in the documentation.
[warning] DipDidSignatureOpts, defined in ./src/utils.ts, is referenced by utils.generateDipDidSignature.generateDipDidSignature.params but not included in the documentation.
[warning] DipIdentityProofOpts, defined in ./src/utils.ts, is referenced by utils.generateDipIdentityProof.generateDipIdentityProof.params but not included in the documentation.
[warning] ProviderStateRootProofOpts, defined in ./src/utils.ts, is referenced by utils.generateProviderStateRootProof.generateProviderStateRootProof.params but not included in the documentation.
[info] Documentation generated at ./docs/api
```

I guess some links are broken? Is that out of scope? Also, please run `yarn version check --interactive` and ignore any version changes. That is to make the developer aware whether the versioning need some major/minor/patch change based on the changes, but of course for the docs you can disregard that.

**Comment by ChrisChinchilla** [comment]
@ntn-x2 OK, I hadn't come across that before. I didn't see an "ignore" option, so picked "decline"?

As for the missing links, it's because areas of the code reference something else that doesn't have documentation added. We can either ignore it or add those docs. They are only warnings. I don't mind.

**Comment by ntn-x2** [comment]
For instance the `SubmittableExtrinsic`.
Screenshot 2024-01-18 at 10 13 48

**Comment by ChrisChinchilla** [comment]
@ntn-x2 Then I guess we need to fill those out, you want to do it or shall I take a pass and you review?

**Comment by ntn-x2** [comment]
The latter, if possible 😄

**Review by ntn-x2 — APPROVED** [review]
Alright, let's try it out then!

**Pull request merged**
